### ISSUE TITLE
RFC: "output-hidden" feature

### ISSUE THREAD

**Issue by matgnt** [abdonrd/moment-element#15]
Hello,

I'd like to use this component to only format my date, but not to render anything into my html. The "output" will be input for another component.

For this, I want to propose an html attribute "output-hidden" to let the component know to not render, but still set the "output" property.

I can create a pull request for this feature.

Thanks for your comments,
Matthias

**Comment by abdonrd** [comment]
I like the idea. In fact, I would have liked to have created it that way (without content) from the beginning. 😅 

But changing it now would be a breaking change. And I don't really like the idea of hiding the content.

**Comment by matgnt** [comment]
Haha, that's good to hear 😄 

How do you mean it's a breaking change? I used "hide" to keep the default behavior with showing the output. Only if the attribute is given, the output is hidden. If it fits better, I could change from "outputHidden" to "hideOutput". Developers who still want to see it, don't have to change anything, right? Since the default of this property is false. And with "dom-if" it's not just hidden, it's not rendered - as far as I understand.
What do you think?

**Comment by abdonrd** [comment]
My proposal to `v3.0.0`: https://github.com/abdonrd/moment-element/pull/16

@matgnt what do you think?

**Comment by abdonrd** [comment]
Released! https://github.com/abdonrd/moment-element/releases/tag/v3.0.0
