### ISSUE TITLE
Better readme.md

### ISSUE THREAD

**Issue by caueops** [abdonrd/moment-element#3]
Hey, congrats for element 👍 

So, what do you think for improve the readme with more informations? Like: How to developing, contribute, tests...

**Comment by abdonrd** [comment]
Thanks! Let me check...

I have a little README.md for webcomponents.org.

**Comment by abdonrd** [comment]
Added [CONTRIBUTING.md](https://github.com/abdonrd/moment-element/blob/master/CONTRIBUTING.md) file!
