### ISSUE TITLE
Auto update content is using from="now"

### ISSUE THREAD

**Issue by NicolasRannou** [abdonrd/moment-element#7]
Because if I create the element "now", in 5mn the value of `moment-element` will not be accurate anymore...

**Comment by NicolasRannou** [comment]
to give a bit more context, I now use it as:
```
          // update timestamp every 5mn
          window.setInterval(function(){
            this.$.datetime.from = '';
            this.$.datetime.from = 'now';
          }.bind(this), 300000);
```

**Comment by abdonrd** [comment]
Thanks for the issue @NicolasRannou!

I think the `computed` doesn't execute because the `from` value is the same:

[abdonrd/moment-element/moment-element.html#L85](https://github.com/abdonrd/moment-element/blob/master/moment-element.html#L85)

Do you want to send a PR with a proposal to fix it?

**Comment by NicolasRannou** [comment]
OK I'll think about which would be a good way to do it!

1- we can  **setInterval** in `moment-element` as I currently use it and expose it behind a special flag such as `update= '1000'` which would be the update interval. `update= '0' (default)` means no auto-update.
```
 // update timestamp every 5mn
 window.setInterval(function(){
   this.$.datetime.from = '';
  this.$.datetime.from = 'now';
}.bind(this), 300000);
```

2- we can add an extra parameter in the computed value watchers to manually re-compute new value...
```
_computeOutput(datetime, inputFormat, outputFormat, from, to, update)
```

3- maybe we can 'notify' somehow that we should recompute the property using some internal polymer methods...

**Comment by NicolasRannou** [comment]
I'll go ahead with options 1-2 if it is fine with you - something like:
```
properties: {
    autoUpdate: {
      type: Number,
      value: 0,
      observer: "_autoUpdateChanged"
    },
    ticker: {
      type: Number,
      value: 0,
      readOnly: true
    },
    tick: {
      type: Boolean,
      value: false,
    },
    output: {
      type: String,
      notify: true,
      output: '_computeOutput(..., tick)'
    }
  },

  _autoUpdateChanged: function() {
    clearInterval(this.ticker);

    if(this.autoUpdate > 0){
      var ticker = this.setInterval(function(){
        this.tick = !this.tick;
      }.bind(this), this.autoUpdate);
      this. _set_ticker(ticker);
    }
  }
```

**Comment by NicolasRannou** [comment]
couple of notes -
`autoUpdate` is a Number so we can directly use it to set the update interval in ms.
`ticker` is private so we can not mess around with it.
We also need to call clearInterval when element is removed, but not sure which would be the best hook to do it: detached?

**Comment by abdonrd** [comment]
I think it is best not to add that responsibility to the element, because it's only a moment wrapper.

**Comment by abdonrd** [comment]
I propose https://github.com/abdonrd/moment-element/pull/8. WDYT? I also added a demo.
